### PR TITLE
QA-13327: Use newly added Progress component from moonstone-alpha

### PR DESCRIPTION
**Pull request by cedmail**
## JIRA

https://jira.jahia.org/browse/QA-13327

## Description

Create a new progress component and use it between every screen

## Tests

The following are included in this PR
- [ ] Unit Tests (Most changes _should_ have unit tests)
- [ ] Integration Tests

## Checklist

I have considered the following implications of my change: 

- [ ] Security (in particular for changes to authentication, authorization, data fetching, ...)
- [ ] Performance
- [ ] Migration
- [ ] Code maintainability

## Documentation

- [ ] Inline documentation
- [ ] Internal Documentation (wiki)
- [ ] User-facing Documentation

### CODE REVIEW

**Review by tdraier — COMMENTED** [review]
As discussed I moved the code to jahia-ui-root and exposes it :   

https://github.com/Jahia/jahia-ui-root/pull/120

I've updated jcontent to use the hook from the new location : 

https://github.com/Jahia/jcontent/pull/379

Other modules will have to be migrated to wp5 to use it

**Comment by cedmail** [comment]
So we need to drop this PR no?

**Comment by cedmail** [comment]
@tdraier what do I do about this PR? drop it?

**Comment by tdraier** [comment]
yes, code has been copied to jahia-ui-root

**Pull request closed without merging**
